---
name: Alien-Libjio
version: 1.000001
author:
  - 'Jonathan Yu <frequency@cpan.org>'
abstract: Installing and finding libjio (Journalled I/O library)
license: unrestricted
requires:
  Carp: 1.04
  ExtUtils::Liblist: 0
  perl: 5.006
  strict: 0
  version: 0.74
  warnings: 0
  IPC::Open3: 0
  Cwd: 0
  File::Spec: 0
build_requires:
  Test::More: 0.62
  Test::NoWarnings: 0.084
  ExtUtils::CBuilder: 0
recommends:
  Perl::Critic: 1.096
  Test::DistManifest: 1.001002
  Test::Kwalitee: 1.01
  Test::MinimumVersion: 0.008
  Test::Perl::Critic: 1.01
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
  Test::Portability::Files: 0.05
  Test::Signature: 1.1
  Test::YAML::Meta: 0.11
dynamic_config: 1
provides:
  Alien::Libjio:
    file: lib/Alien/Libjio.pm
    version: 1.000001
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
resources:
  Ratings: http://cpanratings.perl.org/d/Alien-Libjio
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Alien-Libjio
  license: http://edwardsamuels.com/copyright/beyond/articles/public.html
  repository: http://svn.ali.as/cpan/trunk/Alien-Libjio
